version: "3.8"

services:
  php:
    build: .
    container_name: php-dev-test
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: ["tail", "-f", "/dev/null"]
